services:
  postgres:
    image: postgres:17-alpine
    container_name: caloriex_db
    environment:
      POSTGRES_DB: caloriex_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d caloriex_db" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - caloriex-net

  app:
    build: .
    container_name: caloriex_app
    environment:
      DB_URL: postgres:5432/caloriex_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - caloriex-net

networks:
  caloriex-net:
    driver: bridge

volumes:
  postgres_data: